bbx_nft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_nft_app.urls')),
]

main_nft_app/urls.py
from django.urls import path
from . import  views

app_name = 'item_urls'
urlpatterns = [
# define all app-level URLS in this list
    path('', views.home, name='home'),  
    path("items/", views.ItemIndex.as_view(), name = "index"),
    path('items/create/', views.ItemsCreate.as_view(), name='items_create'),
    path("items/<int:pk>/", views.items_detail, name = "detail"),
    path("items/<int:pk>/metadata/", views.get_json_metadata, name = "json_metadata"),
]

main_nft_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, redirect

# Create your models here.
class Collection(models.Model):
    collection_choice_text = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    
    def __str__(self):
        return f'collection {self.collection_choice_text} by {self.user.id}'

    def get_absolute_url(self):
        return reverse('items:detail', kwargs={'pk': self.item.id})

class Item(models.Model):
    BLOCKCHAIN = (
        ('E', 'Ethereum'),
        ('P', 'Polygon'),
    )
    file = models.CharField(max_length=250, blank=False)
    name = models.CharField(max_length=100, blank=False)
    details_url = models.URLField(max_length=200)
    description = models.TextField()
    properties = models.CharField(max_length=100, blank=False)
    levels = models.CharField(max_length=100, blank=False)
    stats = models.CharField(max_length=100, blank=False)
    unlockable_content = models.BooleanField(default=False)
    explicit_or_sensitive_content = models.BooleanField(default=False)
    supply = models.IntegerField(default=1)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    blockchain = models.CharField(
        max_length=1,
        choices=BLOCKCHAIN)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
        
    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'app_id': self.id})

    

main_nft_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Item, Collection

class ItemForm(ModelForm):
    class Meta: 
        model = Item
        fields = '__all__' 
# Creating a form to add an application
form = ItemForm()

# Creating a form to change an existing application
item = Item.objects.get(pk=1)
form = ItemForm(instance=item)


class CollectionForm(ModelForm):
    class Meta:
        model = Collection
        fields = '__all__'

form = CollectionForm()

# Creating a form to change an existing application
collection = Collection.objects.get(pk=1)
form = CollectionForm(instance=collection)

main_nft_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from .models import Item, Collection
from django.shortcuts import render, redirect
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core import serializers
import json
from json import JSONEncoder


# Create your views here.
class LazyEncoder(DjangoJSONEncoder):
    def default(self):
        item = Item.objects.all()
        if isinstance(Item, item):
            return str(Item)
        return super(LazyEncoder, self).default(Item)


def get_json_metadata(request,pk):
    item = Item.objects.get(id = pk)
    json_metadata = serialize('json', Item.objects.all(), cls=LazyEncoder)
    return render(
      request, 'json_metadata.html',  {
          "json_metadata": json_metadata,
          "item": item,
      }
    )

class ItemIndex(ListView):
    model = Item
    template_name = 'items/index.html'

    def get_queryset(self):
        queryset = Item.objects.filter(user = self.request.user)
        return queryset

def items_detail(request, pk):
    item = Item.objects.get(id = pk)
    return render(
      request,
      "items/detail.html", {
          "item": item,
      }
    )

def home(request):
    return render(request, 'home.html')

class ItemsCreate(CreateView): 
    model = Item
    template_name = 'items/item_form.html'
    fields = '__all__'
    success_url = '/items/'

main_nft_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BingeBuilderX</title>
     <!-- Local CSS -->
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Jquery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
      <!-- Materialize CSS -->
      <link rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     
      <!-- Fontawesome -->
      <script src="https://kit.fontawesome.com/dfeacce2a5.js" crossorigin="anonymous"></script>
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
              <a href="{% url 'item_urls:home' %}" class="brand-logo">BingeBuilderX</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href=""></a></li>
                <li><a href=""></a></li>
                <li><a href="{% url 'item_urls:index' %}">View All My Items</a></li>
              </ul>
            </div>
          </nav>
    </header>

    <main>
        {% block main %}
        {% endblock %}
    </main>

    <footer class="page-footer">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container">
            All Rights Reserved, &copy: 2021 BingeBuilderX
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
          </div>
        </div>
      </footer>
</body>
</html>

main_nft_app/templates/home.html
{% extends "base.html" %}

{% block main %}

<h1>Home</h1>

{% for item in object_list %}

<p>Name: {{ item.name }}</p>
{% endfor %}
{% endblock %}

main_nft_app/templates/items/detail.html
{% extends "base.html" %}
{% block main%}
<div class="container">
    <h1 class="center">{{ item.name }}</h1>
    
    
        <div class="col s12 ">
            <div class="card blue-green darken-1 white purple-border z-depth-3">
                <a href="{% url 'item_urls:json_metadata' item.id %}">
                <div class="card-content black-text">
                    <div class="card-image">
                        <img src="{{ item.file }}" class=""/>
                    </div>
                    <div class="card-action">
                        <span class="card-title">{{item.levels}}</span>
                        <p>{{ item.blockchain | linebreaksbr }}</p>
                        <p>{{ item.properties | linebreaksbr }}</p>
                        <p>{{ item.description | linebreaksbr }}</p>
                    </div>   
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main_nft_app/templates/items/index.html
{% for item in object_list%}

<div class="col s12 m12 l6">
    <a href="{% url 'item_urls:detail' item.id %}">
        <div class="card large darken-1 ">
            <div class = "card-image">
                <br>
                <img src="{{item.file}}" alt="" class="responsive-img"">
            </div>
            <div class="card-content"> 
                <h4> {{item.name}} </h4>
                <h5>{{ item.blockchain }}</h5>
                <span>{{item.collection}}</span>
            </div>
        </div>
    </a>
</div>
{% empty %}

{% endfor %}

main_nft_app/templates/items/item_form.html
{% extends 'base.html' %} {% block main %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_nft_app/templates/json_metadata.html
{% extends "base.html" %}
{% block main%}
<h1>JSON Metadata</h1>
<hr>
<p>{{ json_metadata }}</p>
{% endblock %}